// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suvxmnrnldfhfwxvkntv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dnhtbnJubGRmaGZ3eHZrbnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTAyMzEsImV4cCI6MjA2MTkyNjIzMX0.bwMg4PYkxfGyWQ_ekV6TplRhHUDyz53qy_wIGu_MF44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);